#include "Metrics/Metric__NFK.hpp"
#include "Metrics/Metric__NFK_Adaptive.hpp"
#include "Metrics/Metric__FFK_FMM.hpp"
#include "Metrics/MetricBase.hpp"
#include "Metrics/Metric_Naive.hpp"
#include "Metrics/Metric_FMM.hpp"
#include "Metrics/Metric_FMM_Adaptive.hpp"

#include "Metrics/SquaredDistanceMatrix/SquaredDistanceMatrix__NFK.hpp"
#include "Metrics/SquaredDistanceMatrix/SquaredDistanceMatrix__NFK_Adaptive.hpp"
#include "Metrics/SquaredDistanceMatrix/SquaredDistanceMatrix__FFK_FMM.hpp"
#include "Metrics/SquaredDistanceMatrix/SquaredDistanceMatrix_Naive.hpp"
#include "Metrics/SquaredDistanceMatrix/SquaredDistanceMatrix_FMM.hpp"
#include "Metrics/SquaredDistanceMatrix/SquaredDistanceMatrix_FMM_Adaptive.hpp"

#include "Metrics/TP_Metric/TP_Metric__NFK.hpp"
#include "Metrics/TP_Metric/TP_Metric__NFK_Adaptive.hpp"
#include "Metrics/TP_Metric/TP_Metric__FFK_FMM.hpp"
#include "Metrics/TP_Metric/TP_Metric_Naive.hpp"
#include "Metrics/TP_Metric/TP_Metric_FMM.hpp"
#include "Metrics/TP_Metric/TP_Metric_FMM_Adaptive.hpp"

#include "Metrics/TP_SingularMetric/TP_SingularMetric__NFK.hpp"
#include "Metrics/TP_SingularMetric/TP_SingularMetric__NFK_Adaptive.hpp"
#include "Metrics/TP_SingularMetric/TP_SingularMetric__FFK_FMM.hpp"
//#include "Metrics/TP_SingularMetric/TP_SingularMetric_Naive.hpp"
#include "Metrics/TP_SingularMetric/TP_SingularMetric_FMM.hpp"
#include "Metrics/TP_SingularMetric/TP_SingularMetric_FMM_Adaptive.hpp"

